name: Deploy Heroku

on:
  workflow_call:
    secrets:
      HEROKU_API_KEY:
        required: true

jobs:
  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "maximiliano-rivadeneira"
          heroku_email: "maxirivadeneira92@gmail.com"
          remote_branch: "master"
          usedocker: true
