name: Pipeline

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_EKO_TOKEN:
        required: true
      GITGUARDIAN_API_KEY:
        required: true
      SONAR_TOKEN:
        required: true
      # SNYK_TOKEN:
      #   required: true
      SEMGREP_APP_TOKEN:
        required: true
      HEROKU_API_KEY:
        required: true
  push:
    branches:
      - master
      - develop

jobs:
  security_sast:
    uses: ./.github/workflows/security_sast.yml
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  deploy_to_heroku:
    uses: ./.github/workflows/deploy.yml
    needs: security_sast
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}