name: Security DAST

on:
  workflow_call:
    secrets:
      GITGUARDIAN_API_KEY:
        required: true
      GH_EKO_TOKEN:
        required: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://maximiliano-rivadeneira.herokuapp.com/'
          cmd_options: '-a'